=== kriszkecodecool/XMLTaskNE9JRL/DOMParseNe9jrl/XMLSchemaNE9JRL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/XMLSchemaNE9JRL" elementFormDefault="qualified">
	<xs:element name="database"> <!-- < Létrehozzuk a kezdő objektumunkat. > -->
		<xs:complexType>
			<xs:sequence> <!-- < Definiáljuk a saját típusainkat. > -->
				<xs:element name="category" type="categoryType" minOccurs = "0" maxOccurs="unbounded"/>
				<xs:element name="paymentmethod" type="paymentmethodType" minOccurs = "0" maxOccurs="unbounded"/>
				<xs:element name="user" type="userType" minOccurs = "0" maxOccurs="unbounded"/>
				<xs:element name="shop" type="shopType" minOccurs = "0" maxOccurs="unbounded"/>
				<xs:element name="order" type="orderType" minOccurs = "0" maxOccurs="unbounded"/>
				<xs:element name="review" type="reviewType" minOccurs = "0" maxOccurs="unbounded"/>
				<xs:element name="item" type="itemType" minOccurs = "0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		
		<!-- < Primary key-ek definiálása. > -->
		<xs:key name="UserID">
			<xs:selector xpath="user"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:key name="ShopID">
			<xs:selector xpath="shop"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:key name="OrderID">
			<xs:selector xpath="order"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:key name="ReviewID">
			<xs:selector xpath="review"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:key name="ItemID">
			<xs:selector xpath="item"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:key name="CategoryID">
			<xs:selector xpath="category"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:key name="PaymentMethodID">
			<xs:selector xpath="paymentmethod"/>
			<xs:field xpath="@id"/>
		</xs:key>
		
		<!-- < Foreign key-ek definiálása > -->
		<xs:keyref name="shop-category" refer="CategoryID">
			<xs:selector xpath="shop/category"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="shop-paymentmethod" refer="PaymentMethodID">
			<xs:selector xpath="shop/paymentmethod"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="item-category" refer="CategoryID">
			<xs:selector xpath="item/category"/>
			<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
		<!-- < Létrehozzuk a saját komplex típusainkat, amit előzőleg definiáltunk. > -->

	<xs:complexType name="userType">
		<xs:sequence>
			<xs:element name="Name" type="nameType"/>
			<xs:element name="Password" type="xs:string"/>
			<xs:element name="Address" type="xs:string"/>
			<xs:element name="Email" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="nameType">
		<xs:sequence>
			<xs:element name="FirstName" type="xs:string"/>
			<xs:element name="LastName" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="shopType">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="Category" type="xs:string"/>
			<xs:element name="PaymentMethod" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="orderType">
		<xs:sequence>
			<xs:element name="ShippingDate" type="xs:date"/>
			<xs:element name="PaymentDate" type="xs:date"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="reviewType">
		<xs:sequence>
			<xs:element name="Comment" type="xs:string"/>
			<xs:element name="Type" type="commentType"></xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"></xs:attribute>
	</xs:complexType>

<!-- < Létrehozunk valami enumszerűséget egy simpleType-al. A kommenteknek két típusa lehet, ezzel különböztetjük meg, hogy egy bolthoz kommentelünk, vagy egy termékhez.. > -->
	<xs:simpleType name="commentType" final="restriction" >
	    <xs:restriction base="xs:string">
	        <xs:enumeration value="shop" />
	        <xs:enumeration value="item" />
	    </xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="itemType">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="Category" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="categoryType">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="paymentmethodType">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="fee" type="xs:int"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"></xs:attribute>
	</xs:complexType>

</xs:schema>

=== kriszkecodecool/XMLTaskNE9JRL/DOMParseNe9jrl/bin/hu/domparse/ne9jrl/XMLNE9JRL.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaNE9JRL.xsd">
  <category id="C_0">
    <Name>Elektronikai Termékek</Name>
  </category>
  
  <category id="C_1">
    <Name>Egészségügyi Termékek</Name>
  </category>
  
  <category id="C_2">
    <Name>Könyvek</Name>
  </category>
  
  
  <paymentmethod id="PM_0">
    <Name>Paypal</Name>
    <fee>500</fee>
  </paymentmethod>
  
  <paymentmethod id="PM_1">
    <Name>SimplePay</Name>
    <fee>300</fee>
  </paymentmethod>
  
  <paymentmethod id="PM_2">
    <Name>Banki Átutalás</Name>
    <fee>200</fee>
  </paymentmethod>
  
  
  <user id="U_0">
    <Name>
      <FirstName>Iváncsik</FirstName>
      <LastName>Krisztián</LastName>
    </Name>
    <Password>teszt</Password>
    <Address>Második Utca 1</Address>
    <Email>ivancsik.krisztian@uni-miskolc.hu</Email>
  </user>
  
  <user id="U_1">
    <Name>
      <FirstName>Éles</FirstName>
      <LastName>Gréta</LastName>
    </Name>
    <Password>teszt2</Password>
    <Address>Második Utca 1</Address>
    <Email>eles.greta@barsony-iskola.hu</Email>
  </user>
  
  <user id="U_2">
    <Name>
      <FirstName>Tóth</FirstName>
      <LastName>Elemér</LastName>
    </Name>
    <Password>elemervagyok123</Password>
    <Address>Ötödik Utca 3</Address>
    <Email>elemerapusztito@freemail.hu</Email>
  </user>
  


  <shop id="S_0">
    <Name>Media Markt</Name>
    <Category>>Elektronikai Termékek</Category>
    <PaymentMethod>Paypal</PaymentMethod>
  </shop>
  
  <shop id="S_1">
    <Name>Alza</Name>
    <Category>Egészségügyi Termékek</Category>
    <PaymentMethod>SimplePay</PaymentMethod>
  </shop>
  
  <shop id="S_2">
    <Name>Libri</Name>
    <Category>Könyvek</Category>
    <PaymentMethod>Banki Átutalás</PaymentMethod>
  </shop>
  

  <order id="O_0">
    <ShippingDate>2022-03-04</ShippingDate>
    <PaymentDate>2022-03-01</PaymentDate>
  </order>
  
  <order id="O_1">
    <ShippingDate>2023-01-15</ShippingDate>
    <PaymentDate>2023-01-12</PaymentDate>
  </order>
  
  <order id="O_2">
    <ShippingDate>2023-01-10</ShippingDate>
    <PaymentDate>2023-01-09</PaymentDate>
  </order>
  
  
  <review id="R_0">
    <Comment>A bolt nem akarja visszavenni a hibás terméket amit küldött.</Comment>
    <Type>shop</Type>
  </review>
  
  <review id="R_1">
    <Comment>Nagyon segítőkész a support!</Comment>
    <Type>shop</Type>
  </review>
  
  <review id="R_2">
    <Comment>Imádom ezt a terméket!</Comment>
    <Type>item</Type>
  </review>
  

  <item id="I_0">
    <Name>Pendrive</Name>
    <Category>Elektronikai Termékek</Category>
  </item>
  
  <item id="I_1">
    <Name>C Vitamin</Name>
    <Category>Egészségügyi Termékek</Category>
  </item>
  
  <item id="I_2">
    <Name>Dracula</Name>
    <Category>Könyvek</Category>
  </item>
</database>
